In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("assets/datasets/billboard.csv")

In [6]:
print df.head()

   year      artist.inverted                                  track  time  \
0  2000      Destiny's Child               Independent Women Part I  3:38
1  2000              Santana                           Maria, Maria  4:18
2  2000        Savage Garden                     I Knew I Loved You  4:07
3  2000              Madonna                                  Music  3:45
4  2000  Aguilera, Christina  Come On Over Baby (All I Want Is You)  3:38

  genre date.entered date.peaked  x1st.week  x2nd.week  x3rd.week     ...      \
0  Rock   2000-09-23  2000-11-18         78       63.0       49.0     ...
1  Rock   2000-02-12  2000-04-08         15        8.0        6.0     ...
2  Rock   1999-10-23  2000-01-29         71       48.0       43.0     ...
3  Rock   2000-08-12  2000-09-16         41       23.0       18.0     ...
4  Rock   2000-08-05  2000-10-14         57       47.0       45.0     ...

   x67th.week  x68th.week  x69th.week  x70th.week  x71st.week  x72nd.week  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN

   x73rd.week  x74th.week  x75th.week  x76th.week
0         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN

[5 rows x 83 columns]

In [42]:
# df describe provides a good overall summery of the numerical values in the data frame.
# it shows some detail including count, mean, min/max, standard deviation, and quartiles

df.describe()

/Users/work/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,year,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,x6th.week,x7th.week,x8th.week,x9th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
count,317.0,317.000000,312.000000,307.000000,300.000000,292.000000,280.000000,269.000000,260.000000,253.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2000.0,79.958991,71.173077,65.045603,59.763333,56.339041,52.360714,49.219331,47.119231,46.343874,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.0,14.686865,18.200443,20.752302,22.324619,23.780022,24.473273,25.654279,26.370782,27.136419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2000.0,15.000000,8.000000,6.000000,5.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2000.0,74.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2000.0,81.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2000.0,91.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2000.0,100.000000,100.000000,100.000000,100.000000,100.000000,99.000000,100.000000,99.000000,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 83 columns):
year               317 non-null int64
artist.inverted    317 non-null object
track              317 non-null object
time               317 non-null object
genre              317 non-null object
date.entered       317 non-null object
date.peaked        317 non-null object
x1st.week          317 non-null int64
x2nd.week          312 non-null float64
x3rd.week          307 non-null float64
x4th.week          300 non-null float64
x5th.week          292 non-null float64
x6th.week          280 non-null float64
x7th.week          269 non-null float64
x8th.week          260 non-null float64
x9th.week          253 non-null float64
x10th.week         244 non-null float64
x11th.week         236 non-null float64
x12th.week         222 non-null float64
x13th.week         210 non-null float64
x14th.week         204 non-null float64
x15th.week         197 non-null float64
x16th.week         182 non-null float64
x17th.week         177 non-null float64
x18th.week         166 non-null float64
x19th.week         156 non-null float64
x20th.week         146 non-null float64
x21st.week         65 non-null float64
x22nd.week         55 non-null float64
x23rd.week         48 non-null float64
x24th.week         46 non-null float64
x25th.week         38 non-null float64
x26th.week         36 non-null float64
x27th.week         29 non-null float64
x28th.week         24 non-null float64
x29th.week         20 non-null float64
x30th.week         20 non-null float64
x31st.week         19 non-null float64
x32nd.week         18 non-null float64
x33rd.week         12 non-null float64
x34th.week         10 non-null float64
x35th.week         9 non-null float64
x36th.week         9 non-null float64
x37th.week         9 non-null float64
x38th.week         8 non-null float64
x39th.week         8 non-null float64
x40th.week         7 non-null float64
x41st.week         7 non-null float64
x42nd.week         6 non-null float64
x43rd.week         6 non-null float64
x44th.week         6 non-null float64
x45th.week         5 non-null float64
x46th.week         5 non-null float64
x47th.week         5 non-null float64
x48th.week         4 non-null float64
x49th.week         4 non-null float64
x50th.week         4 non-null float64
x51st.week         4 non-null float64
x52nd.week         4 non-null float64
x53rd.week         4 non-null float64
x54th.week         2 non-null float64
x55th.week         2 non-null float64
x56th.week         2 non-null float64
x57th.week         2 non-null float64
x58th.week         2 non-null float64
x59th.week         2 non-null float64
x60th.week         2 non-null float64
x61st.week         2 non-null float64
x62nd.week         2 non-null float64
x63rd.week         2 non-null float64
x64th.week         2 non-null float64
x65th.week         1 non-null float64
x66th.week         0 non-null float64
x67th.week         0 non-null float64
x68th.week         0 non-null float64
x69th.week         0 non-null float64
x70th.week         0 non-null float64
x71st.week         0 non-null float64
x72nd.week         0 non-null float64
x73rd.week         0 non-null float64
x74th.week         0 non-null float64
x75th.week         0 non-null float64
x76th.week         0 non-null float64
dtypes: float64(75), int64(2), object(6)
memory usage: 205.6+ KB

In [92]:
# Median: Median ranking for each track.

def median(x):
    for i in df.ix[x, 7:].values:
        print np.nanmedian(i), df.ix[x, 2]
        return
for i in range(317):
    new_func(i)

78.0 Independent Women Part I
15.0 Maria, Maria
71.0 I Knew I Loved You
41.0 Music
57.0 Come On Over Baby (All I Want Is You)
59.0 Doesn't Really Matter
83.0 Say My Name
63.0 Be With You
77.0 Incomplete
81.0 Amazed
82.0 It's Gonna Be Me
71.0 What A Girl Wants
70.0 Everything You Want
84.0 With Arms Wide Open
59.0 Try Again
60.0 Bent
82.0 Thank God I Found You
81.0 Breathe
72.0 Case Of The Ex (Whatcha Gonna Do)
99.0 He Loves U Not
63.0 He Wasn't Man Enough
77.0 You Sang To Me
51.0 Give Me Just One Night (Una Noche)
74.0 Jumpin' Jumpin'
81.0 Kryptonite
74.0 Thong Song
50.0 I Turn To You
81.0 My Love Is Your Love
94.0 I Wanna Know
92.0 Get It On.. Tonite
42.0 Bye Bye Bye
70.0 The Real Slim Shady
85.0 Most Girls
85.0 Gotta Tell You
73.0 Bring It All To Me
36.0 Hot Boyz
68.0 I Try
68.0 This I Promise You
76.0 No More
74.0 Show Me The Meaning Of Being Lonely
85.0 Absolutely (Story Of A Girl)
74.0 That's The Way It Is
89.0 All The Small Things
67.0 Blue (Da Ba Dee)
67.0 Bag Lady
25.0 There U Go
81.0 Higher
100.0 (Hot S**t) Country Grammar
85.0 Wifey
89.0 Auld Lang Syne (The Millenium Mix)
67.0 It Feels So Good
67.0 Oops!.. I Did It Again
39.0 Shape Of My Heart
77.0 Wonderful
85.0 Between Me And You
77.0 I Need You
83.0 Then The Morning Comes
58.0 I Just Wanna Love U (Give It 2 Me)
77.0 Let's Get Married
91.0 Take A Picture
38.0 She Bangs
97.0 Shake Ya Ass
99.0 Back Here
76.0 From The Bottom Of My Broken Heart
65.0 Never Let You Go
80.0 Otherside
52.0 Liar
77.0 Pinch Me
54.0 He Can't Love U
57.0 Wobble Wobble
98.0 Desert Rose
69.0 Big Pimpin'
63.0 Only God Knows Why
80.0 Learn To Fly
40.0 Goodbye Earl
46.0 Dancin'
48.0 Bounce With Me
96.0 Swear It Again
76.0 Meet Virginia
75.0 I Wish
22.0 This Time Around
63.0 I Think I'm In Love With You
89.0 What's Your Fantasy
83.0 Callin' Me
72.0 Don't Say You Love Me
94.0 Faded
90.0 Yes!
74.0 Shake Your Bon-Bon
64.0 You're A God
62.0 Separated
71.0 Big Deal
84.0 Stay The Night
78.0 The Next Episode
61.0 Lucky
75.0 Crash And Burn
66.0 Don't Think I'm Not
85.0 I Like It
74.0 Broadway
69.0 I Wanna Be With You
75.0 Forgot About Dre
77.0 Untitled (How Does It Feel)
78.0 That's The Way
70.0 My First Love
80.0 A Puro Dolor (Purest Of Pain)
71.0 What'Chu Like
88.0 Party Up (Up In Here)
79.0 Cowboy Take Me Away
73.0 My Next Thirty Years
97.0 Best Of Intentions
79.0 Better Off Alone
69.0 Another Dumb Blonde
83.0 I Learned From The Best
84.0 Hanginaround
90.0 Shackles (Praise You)
28.0 Crybaby
85.0 My Best Friend
70.0 Falls Apart
43.0 American Pie
81.0 Where I Wanna Be
71.0 We Danced
78.0 What About Now
58.0 The One
77.0 How Do You Like Me Now?!
73.0 The Best Day
80.0 Without You
89.0 Just Friends (Sunny)
88.0 What Do You Say
76.0 Just Be A Man About It
90.0 Rhythm Divine
91.0 I Will Love Again
64.0 It's My Life
77.0 Born To Fly
75.0 I Lost It
96.0 One Night Stand
94.0 Love Is Blind
84.0 I Don't Wanna
81.0 The Little Girl
99.0 Aaron's Party (Come Get It)
81.0 Just Another Day In Paradise
86.0 You Can Do It
89.0 Back At One
80.0 Dance Tonight
76.0 It Must Be Love
81.0 She's More
50.0 Simple Kind Of Life
77.0 911
87.0 Prayin' For Daylight
81.0 Graduation (Friends Forever)
86.0 One Voice
89.0 Smile
79.0 Buy Me A Rose
80.0 Lessons Learned
71.0 Go On
92.0 Got To Get It
99.0 Who Let The Dogs Out
73.0 The Chain Of Love
79.0 Love's The Only House
99.0 Sexual (Li Da Di)
74.0 Kiss This
78.0 I Will.. But
91.0 Couldn't Last A Moment
78.0 Whoa!
79.0 Pop A Top
87.0 Been There
75.0 The Light
75.0 Carlene
75.0 www.memory
86.0 The Itch
77.0 G'D Up
75.0 Whatever
77.0 Emotional
94.0 None Of Ur Friends Business
97.0 Unconditional
98.0 What You Want
56.0 Someday Out Of The Blue
49.0 Nothing As It Seems
85.0 The Best Of Me
95.0 Flowers On The Wall
78.0 Stan
89.0 I'll Be
79.0 Feelin' Good
81.0 Your Everything
63.0 Dear Lie
82.0 Feels Like Love
74.0 Could I Have This Kiss Forever
70.0 The Bad Touch
85.0 Angels
83.0 Because You Love Me
82.0 Country Comes To Town
72.0 Girls Dem Sugar
83.0 Let's Make Love
84.0 Caught Out There
72.0 Anything
76.0 Loser
95.0 You'll Always Be Loved By Me
79.0 What I Need To Do
86.0 No More Rain (In This Cloud)
93.0 That's What I'm Looking For
82.0 This Woman Needs
75.0 Last Resort
76.0 Open My Heart
94.0 Bad Boyz
79.0 The Great Beyond
81.0 It's Always Somethin'
76.0 Some Things Never Change
79.0 Taking You Home
87.0 The Way I Am
74.0 You Owe Me
75.0 Change Your Mind
65.0 Best Friend
79.0 There You Are
68.0 Pop Ya Collar
80.0 No Matter What They Say
63.0 I Don't Wanna Kiss You Goodnight
97.0 Deck The Halls
71.0 I Think God Can Explain
73.0 Where You Are
87.0 Mirror Mirror
81.0 U Don't Love Me
77.0 Treat Her Like A Lady
83.0 Deep Inside
91.0 You Should've Told Me
80.0 That Other Woman
86.0 It Was
77.0 Rollin'
77.0 I Need A Hot Girl
95.0 Do It Again (Put Ya Hands Up)
84.0 More
80.0 Cold Day In July
82.0 As We Lay
98.0 What's My Name
76.0 Private Emotion
68.0 If I Am
97.0 Give Me You
72.0 Californication
80.0 Deep Inside Of You
86.0 Do What You Gotta Do
74.0 Original Prankster
82.0 My Baby You
71.0 Same Script, Different Cast
93.0 Left & Right
78.0 I Belong To You
98.0 That's The Kind Of Mood I'm In
71.0 Breathe And Stop
82.0 Can't Fight The Moonlight
99.0 Tha Block Is Hot
87.0 Baby Don't Cry (Keep Ya Head Up II)
73.0 Sleepwalker
100.0 Left, Right, Left
94.0 N 2 Gether Now
86.0 Ryde or Die, Chick
95.0 Whistle While You Twurk
95.0 Live, Laugh, Love
86.0 No Leaf Clover (Live)
86.0 Another Nine Minutes
75.0 Tricky Tricky
96.0 It's So Hard
98.0 When You Need My Love
79.0 How Many Licks?
75.0 A Little Gasoline
93.0 A Country Boy Can Survive
99.0 My Love Goes On And On
81.0 Put Your Hand In Mine
86.0 I Disappear
98.0 Hey Papi
94.0 The Rockafeller Skank
84.0 Mr. Too Damn Good
95.0 Stay Or Let It Go
80.0 Smoke Rings In The Dark
97.0 The Best Man I Can Be
95.0 Monica
77.0 No Me Dejes De Querer
79.0 Sour Girl
87.0 Daddy Won't Sell The Farm
97.0 You Won't Be Lonely Now
87.0 Meanwhile Back At The Ranch
82.0 Summer Rain
85.0 Real Live Woman
99.0 Shut Up
98.0 Straight Up
94.0 What Means The World To You
85.0 U Understand
84.0 Can't Stay
90.0 Can't Go For That
96.0 West Side Story
87.0 Me Neither
94.0 Take That
91.0 The Hardest Part Of Breaking Up (Is Getting Back Your Stuff)
98.0 Don't Call Me Baby
89.0 Got It All
91.0 Re-Arranged
95.0 Still In My Heart
97.0 3 Little Words
98.0 If You Don't Wanna Love Me
96.0 Baby U Are
99.0 L.A. Song
98.0 The Quittin' Kind
92.0 Do You
92.0 Love Sets You Free
92.0 Riddle
100.0 No Mercy
92.0 I'm Outta Love
97.0 Pull Over
100.0 Ta Da
97.0 Dancing Queen
96.0 Where I Wanna Be
96.0 All Good?
100.0 Get Up
98.0 Spanish Guitar
98.0 I Know
99.0 Imagine That
98.0 Souljas
98.0 Cherchez LaGhost
99.0 Freakin' It
99.0 Kernkraft 400
99.0 Got Beef
99.0 Toca's Miracle

In [75]:
Mean: Average time on chart per genre

gens = []
for i in df['genre']:
    if i not in gens:
        gens.append(i)
def avg_place(gen):
    sum_num = sum(pd.value_counts(df.ix[df['genre'] == gen]['x1st.week']))
    sum_place = sum(df.ix[df['genre'] == gen]['x1st.week'])
    print 'The average place on the Billboard Chart for a', gen, 'track in week 1 was',sum_place / sum_num

for i in gens:
    avg_place(i)

The average place on the Billboard Chart for a Rock track in week 1 was 76
The average place on the Billboard Chart for a Latin track in week 1 was 73
The average place on the Billboard Chart for a Country track in week 1 was 82
The average place on the Billboard Chart for a Rap track in week 1 was 85
The average place on the Billboard Chart for a Pop track in week 1 was 79
The average place on the Billboard Chart for a Electronica track in week 1 was 84
The average place on the Billboard Chart for a Jazz track in week 1 was 89
The average place on the Billboard Chart for a R&B track in week 1 was 84
The average place on the Billboard Chart for a Reggae track in week 1 was 72
The average place on the Billboard Chart for a Gospel track in week 1 was 76

In [45]:
#Variance 
print np.var(df)

year             0.000000
x1st.week      215.023555
x2nd.week      330.194403
x3rd.week      429.255249
x4th.week      496.727322
x5th.week      563.552859
x6th.week      596.802028
x7th.week      655.695388
x8th.week      692.743476
x9th.week      733.474636
x10th.week     789.307041
x11th.week     840.935794
x12th.week     831.050808
x13th.week     865.009161
x14th.week     927.507978
x15th.week     989.878018
x16th.week    1011.985509
x17th.week    1088.974688
x18th.week    1095.217158
x19th.week    1083.497863
x20th.week    1074.373851
x21st.week     403.042840
x22nd.week     438.267769
x23rd.week     325.610677
x24th.week     336.865784
x25th.week     341.851108
x26th.week     356.500000
x27th.week     376.087990
x28th.week     252.416667
x29th.week     220.627500
                 ...
x47th.week     218.960000
x48th.week     160.500000
x49th.week     193.500000
x50th.week     257.500000
x51st.week     270.687500
x52nd.week     222.187500
x53rd.week     219.187500
x54th.week       6.250000
x55th.week       0.250000
x56th.week       0.250000
x57th.week       2.250000
x58th.week       0.250000
x59th.week      12.250000
x60th.week       1.000000
x61st.week       0.250000
x62nd.week       6.250000
x63rd.week       6.250000
x64th.week       0.000000
x65th.week       0.000000
x66th.week            NaN
x67th.week            NaN
x68th.week            NaN
x69th.week            NaN
x70th.week            NaN
x71st.week            NaN
x72nd.week            NaN
x73rd.week            NaN
x74th.week            NaN
x75th.week            NaN
x76th.week            NaN
dtype: float64